title: "Mi Proyecto de Ciencia de Datos"
description: "Presentación de los análisis y hallazgos obtenidos a partir de los datos educativos."
theme: jekyll-theme-minima
url: "https://Amath3o.github.io/Proyecto_Cs_Datos_Pagina"
baseurl: "" 

